// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkcPeTZaVEakwpeuyxNfUA6msoOkqoa8',
    appId: '1:849967855789:web:1de9fb454f01ce78a62e24',
    messagingSenderId: '849967855789',
    projectId: 'ems-1-3d55e',
    authDomain: 'ems-1-3d55e.firebaseapp.com',
    storageBucket: 'ems-1-3d55e.appspot.com',
    measurementId: 'G-XRKD69TPG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgia04QIIgzl1woaZr64MzsXVgRG5f4Q',
    appId: '1:849967855789:android:4f0d5a2825ee8a17a62e24',
    messagingSenderId: '849967855789',
    projectId: 'ems-1-3d55e',
    storageBucket: 'ems-1-3d55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzLHXCihL3uh7UXHl18SLpchOtjKC2i0',
    appId: '1:849967855789:ios:f793c1cda25a281aa62e24',
    messagingSenderId: '849967855789',
    projectId: 'ems-1-3d55e',
    storageBucket: 'ems-1-3d55e.appspot.com',
    iosBundleId: 'com.example.sems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdzLHXCihL3uh7UXHl18SLpchOtjKC2i0',
    appId: '1:849967855789:ios:091c4c251123b2e8a62e24',
    messagingSenderId: '849967855789',
    projectId: 'ems-1-3d55e',
    storageBucket: 'ems-1-3d55e.appspot.com',
    iosBundleId: 'com.example.sems.RunnerTests',
  );
}
